### ISSUE TITLE
Link to team page broken for rna-seq workshop page

### ISSUE THREAD

**Issue by mdehollander** [gallantries/gallantries#5]
Nice initiative and website!

Small bug in the rna-seq workshop page: on https://galaxy-carpentries.github.io/gallantries/event/2019-03-25-first-galantries-workshop/ the link to the team page is https://galaxy-carpentries.github.io/team.html but should be https://galaxy-carpentries.github.io/gallantries/team

**Comment by shiltemann** [comment]
Hi @mdehollander :)

Thanks for reporting the issue, I just merged an open PR by @bebatut which I believe fixes the issue, thanks for the reminder!
